services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - orders_net

  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers=8
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./tests:/app/tests
      - ./pytest.ini:/app/pytest.ini
      - ./alembic.ini:/app/alembic.ini
      - ./.env:/app/.env
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - orders_net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - orders_net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - orders_net

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1001
      KAFKA_RESERVED_BROKER_MAX_ID: 2000
    networks:
      - orders_net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-consumer:
    build: .
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: python -m app.kafka.consumer
    restart: always
    volumes:
      - ./app:/app/app
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - orders_net

  celery:
    build: .
    command: python3 -m celery -A app.tasks worker --loglevel=DEBUG
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - orders_net


networks:
  orders_net:
    driver: bridge

volumes:
  postgres_data: